FROM intel/video-analytics-serving:0.6.1-dlstreamer-edge-ai-extension

LABEL Description="Intel DLStreamer azure video analytics extension with paho mqtt"
LABEL Vendor="scalers.ai"

ENV DEBIAN_FRONTEND noninteractive

ENV http_proxy=
ENV https_proxy=

USER root

# install paho-mqtt python package
RUN pip3 install paho-mqtt

USER vaserving